#!/bin/bash

bspc monitor -d 一 二 三 四 五 六 七 八

#for i in $(bspc query -D --names)
#do
    #bsp-layout set tall $i -- --master-size 0.65 &
#done
bspc config border_width         3
bspc config focused_border_color "#6C6F93"
bspc config normal_border_color "#282e3a"
